### ISSUE TITLE
Holer闪退问题

### ISSUE THREAD

**Issue by chasingML** [Wisdom-Projects/holer#1]
请问大佬，启动之后出现闪退这个怎么破

**Comment by Dom-Wang** [comment]
看下你的环境上是否安装了Java，使用前先安装Java

**Comment by chasingML** [comment]
@Dom-Wang 已经安装过jdk1.8

**Comment by YangFei1929** [comment]
大神,我刚跑了一会然后就不行了,再双击startup.bat就一直闪退了

**Comment by YangFei1929** [comment]
我刚换了个映射端口又可以了,奇怪

**Comment by Dom-Wang** [comment]
控制台会打印提示内容

**Comment by YangFei1929** [comment]
现在是非常不稳的吗?过了一会又不行连不上了,怎么能获取稳定的访问呢,大神?

**Comment by Dom-Wang** [comment]
建议开通独享的Holer Access Key，这样能稳定

**Comment by Dom-Wang** [comment]
最新的软件包，启动holer失败不会立即退出，会显示具体失败的原因。
