### ISSUE TITLE
登录web页面卡死

### ISSUE THREAD

**Issue by Shimada666** [wisdom-projects/holer#12]
自搭服务端,系统ubuntu16.04 openjdk8, 第一次使用时一切正常,但是第二天登录web界面时 在登录密码处卡死 无法恢复正常 尝试重装 无效

**Comment by Dom-Wang** [comment]
清理一下浏览器缓存

**Comment by Shimada666** [comment]
不是浏览器缓存的问题,手机电脑都卡死 手机第一次登陆呢




------------------ 原始邮件 ------------------
发件人: "Dom Wang"<notifications@github.com>;
发送时间: 2019年7月13日(星期六) 下午4:40
收件人: "wisdom-projects/holer"<holer@noreply.github.com>;
抄送: "郑明樟"<649940882@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wisdom-projects/holer] 登录web页面卡死 (#12)



清理一下浏览器缓存
