### ISSUE TITLE
开源

### ISSUE THREAD

**Issue by sky-daiji** [wisdom-projects/holer#13]
@Dom-Wang   老哥，你的项目直接全部开源，搞啥收费啊

**Comment by Dom-Wang** [comment]
用户如果有公网服务器，可以下载搭建自己的holer服务端，如果没有，可以使用holer服务端，收取一点赞助费而已哦

**Comment by Dom-Wang** [comment]
服务端源码地址：https://github.com/wisdom-projects/holer-server
