### ISSUE TITLE
我是来给好评的，太给力了，4G网卡基本不卡顿，甚至还可以通过pycharm远程编译

### ISSUE THREAD

**Issue by JingyunLiang** [wisdom-projects/holer#15]
一直想在家控制办公室的电脑，无奈没有公网ip，`autossh`、`nat123`鼓捣了好久，最后5块钱买了十天试用，完美的解决了我的问题，内网穿透很强。打算先再买半年。

**Comment by Dom-Wang** [comment]
谢谢支持！

**Comment by sky-daiji** [comment]
@MichaelLiang12     让群主开源吧？  钱这么重要嘛？  kubernetes二进制包 要花钱嘛

**Comment by pcdddddd** [comment]
跟frp相比如何?哪个响应速度更快?
