### ISSUE TITLE
请问nginx版本是多少？启动后各种找不到文件。另外开机启动脚本不支持Ubuntu 18。

### ISSUE THREAD

**Issue by zhuwenbing** [wisdom-projects/holer#17]
如题。谢谢！ps：系统环境为Ubuntu 18.04

**Comment by Dom-Wang** [comment]
Ubuntu 18.04是支持的，使用前需要切换至bash模式，执行命令bash切换
执行`bash setup-service.sh`设置开机启动
执行`bash startup.sh`启动软件
nginx没有版本限制的，指定顶级路径即可，确保路径下存在nginx/conf/**nginx.conf**

例如：  
nginx:
    home: /usr/local/nginx
