### ISSUE TITLE
nginx + windows10  Unable to connect holer server <192.168.1.103:6060>

### ISSUE THREAD

**Issue by SilurianYang** [wisdom-projects/holer#25]
## 操作步骤
1.  下载 [holer-client-v1.2.zip](https://github.com/wisdom-projects/holer/releases)
2. 修改  `holer-client\conf\holer.conf`
```js
// holer.conf
HOLER_ACCESS_KEY=HOLER_CLIENT-2A623FCB6E2A7D1D
HOLER_SERVER_HOST=192.168.1.103
```
3.  双击 `startup.bat`
![QQ截图20210529230409](https://user-images.githubusercontent.com/31280665/120075023-33397200-c0d2-11eb-9d46-0e5bb6844f40.jpg)

4.  访问 `holer65532.wdom.net` 重定向到 `http://www.wdom.net/`  访问 `holer.org:65532` 如下图
![QQ截图20210529230604](https://user-images.githubusercontent.com/31280665/120075083-78f63a80-c0d2-11eb-89a9-f77567437dfb.jpg)

## 自我排除

1. 关闭 windows 防火墙 无效
2. `netstat -ano|findstr "6060"` 未找到端口
3. `127.0.0.1` 正常访问

## holer-client/logs 日志
```js
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
Unable to connect holer server <192.168.1.103:6060>
```
## 软件及设备
1. Windows 10 专业版 64位
2. nginx-1.18.0
3. holer-client-v1.2
4. java 版本
``` sh
C:\Users\16067>java -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```

**Comment by WisdomFamily** [comment]
用自搭建的holer服务端，需要设置HOLER_SERVER_HOST=公网IP，而且这个必须是公网IP地址，才能做公网访问本地。
如果是用公开的holer access key，不要设置HOLER_SERVER_HOST参数。
