### ISSUE TITLE
按照教程自己架设的服务端A,在另外一台机器B上安装了客户端,无法访问通过公网访问B的内部端口

### ISSUE THREAD

**Issue by hmleo** [wisdom-projects/holer#27]
机器A上安装了服务端,并启动服务,
机器B上安装了客户端,并设置了密钥与服务端ip,启动之后显示正常, http://{机器A的IP}:600 页面打开也是正常,同时显示 本机B处于在线状态. 如图
![image](https://user-images.githubusercontent.com/16745216/127905361-3bd503f5-4f43-415f-8bf4-028c5006b783.png)

我在机器C上 使用地址 http://112.22.2.xxx:9001 进行访问无法链接(机器B上 http://localhost:9001是没问题的)，
大神帮忙看看 是哪边出问题了，感觉大概率我配置有问题，求指教

**Comment by hmleo** [comment]
![image](https://user-images.githubusercontent.com/16745216/127905552-dd69087f-620b-416f-a5d9-91e7501c070d.png)

**Comment by hmleo** [comment]
![image](https://user-images.githubusercontent.com/16745216/127905662-aee26676-f2ae-4ab3-9d91-7cffeb31457e.png)

**Comment by hmleo** [comment]
![image](https://user-images.githubusercontent.com/16745216/127905754-13f5535d-8dd8-45dd-9faa-9f545924433c.png)

**Comment by WisdomFamily** [comment]
搭建服务端的注意事项：
搭建Holer服务端准备工作
(1) 准备一台Linux系统或者Windows系统主机，实现**公网访问则需要公网IP支持**；

(2) 安装Java 1.8及以上版本，执行命令 java -version 检查Java是否可用；

(3) 安装并启动Nginx, 建议安装其稳定版本；

(4) **设置安全规则，允许访问Holer服务端端口6060、600以及端口映射规则所涉及的端口**；

(5) 建议申请域名并且完成域名备案，并设置域名泛解析（*.域名）和直接解析主域名（@.域名），如果没有域名可以直接使用IP和端口访问。

**Comment by hmleo** [comment]
> 搭建服务端的注意事项：
> 搭建Holer服务端准备工作
> (1) 准备一台Linux系统或者Windows系统主机，实现**公网访问则需要公网IP支持**；
> 
> (2) 安装Java 1.8及以上版本，执行命令 java -version 检查Java是否可用；
> 
> (3) 安装并启动Nginx, 建议安装其稳定版本；
> 
> (4) 设置安全规则，允许访问Holer服务端端口6060、600**以及端口映射规则所涉及的端口**；
> 
> (5) 建议申请域名并且完成域名备案，并设置域名泛解析（*.域名）和直接解析主域名（@.域名），如果没有域名可以直接使用IP和端口访问。

谢谢，是我理解错了，正确访问方式 应该    http://{服务器公网ip}:{映射公网端口}，
我理解成了 http://{客户端机器公网ip}:{映射公网端口}，
