### ISSUE TITLE
可不可以像frp一样公开源码，想学习

### ISSUE THREAD

**Issue by bob4jcom** [Wisdom-Projects/holer#5]
可不可以像frp一样公开源码，想学习

**Comment by Dom-Wang** [comment]
holer客户端的代码已经是开源的，服务端的技术涉及的东西比较多，暂不开源

**Comment by Dom-Wang** [comment]
Holer服务端软件下载链接
https://github.com/wisdom-projects/holer/releases/download/v1.1/holer-server-1.1.zip
