### ISSUE TITLE
服务端可以开源吗？

### ISSUE THREAD

**Issue by zsf513** [wisdom-projects/holer#8]
你好，你这个只有客户端的代码开源了，服务端的代码可以开源吗？

**Comment by Dom-Wang** [comment]
服务端涉及的东西很多，很杂，后续会整理并完善以后会开源的。

**Comment by zsf513** [comment]
期待服务端也开源

**Comment by Dom-Wang** [comment]
服务端软件下载地址
https://github.com/wisdom-projects/holer/releases/download/v1.1/holer-server-1.1.zip

**Comment by Dom-Wang** [comment]
服务端源码地址：https://github.com/wisdom-projects/holer-server
